version: '2'
services:
  app:
    build: docker/local/.
    volumes:
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/app
    depends_on:
      - database
      - redis
    ports:
      - "80:80"
    environment:
      - APP_ENVIRONMENT=local
      - CONTAINER_ROLE=app

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret2
      MYSQL_USER: forge

  redis:
    image: redis:7.0.4-alpine
    command: redis-server --port 6379 --requirepass 4uUG3eff2saxlkjdhjn12kgh
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=4uUG3eff2saxlkjdhjn12kgh
    volumes:
      - ./docker-data/redis:/data
